FROM ubuntu:16.04
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

COPY cluster_test.py /root/
COPY requirements.txt /tmp/requirements.txt

# Provision container
RUN apt-get update \
  && apt-get install -y python3-pip python3-dev \
  && pip3 install --upgrade pip

RUN pip3 install -r /tmp/requirements.txt
